### ISSUE TITLE
[Bug]: Unable to fetch contests in the app.

### ISSUE THREAD

**Issue by skj-skj** [sahej-dev/Snow#15]
### Bug Description

after installing app with new signature.
I am getting this error
"Unable to fetch contests. Please ensure network connectivity and retry."

### How to Reproduce

1. Uninstall old snow app.
2. Install Snow 1.3.3 new signature app.
3. Open app

### Expected Behavior

Show Contest

### Operating System

Android 13

### Snow Version(s)

1.3.3

### Screenshots

![Screenshot_2023-12-14-10-14-32-80_ef7c233286dc178bdec8ebd6c69ed10b](https://github.com/sahej-dev/Snow/assets/53490263/a6843e5a-6376-4d4c-863e-e2066905e52b)

**Comment by mmohammadi9812** [comment]
It seems to be the problems with [the API](https://github.com/sahej-dev/Snow/blob/b2b1622ded672c472b91b3eeac8278dbed28dbfc/packages/contests_repository/lib/src/constants.dart#L6) that's being used in the app. It's [down](https://www.isitdownrightnow.com/kontests.net.html). It should be changed or be swapped with other strategies like using contest sites themselves

**Comment by sahej-dev** [comment]
Hi. I am in the process of writing a custom backend for the app. However, it might take a while as I am very busy with my day job now-a-days. Thank you for using Snow.

**Comment by sahej-dev** [comment]
This has been fixed in 478febd7b121d9dffe4e3738f947b58a0e43eb15. A new API has been developed in Go and deployed at [api.snow.sahej.io](https://api.snow.sahej.io). Source for the same can be found at [sahej-dev/Programming-Contests-Schedule-Api](https://github.com/sahej-dev/Programming-Contests-Schedule-Api).

I'll create a release with the changes soon.
